let cust_data=[{"id":1,"first_name":"Axel","email":"ailiffe0@ftc.gov","location":"Damanhūr"},
{"id":2,"first_name":"Gleda","email":"gdorgan1@upenn.edu","location":"Chengjiao"},
{"id":3,"first_name":"Tulley","email":"trawle2@who.int","location":"Jawornik"},
{"id":4,"first_name":"Xymenes","email":"xwoodyear3@fc2.com","location":"Apopa"},
{"id":5,"first_name":"Payton","email":"proutham4@github.com","location":"Taverny"},
{"id":6,"first_name":"Candida","email":"cskerme5@wix.com","location":"Mendez-Nuñez"},
{"id":7,"first_name":"Wildon","email":"wanstie6@delicious.com","location":"Pamyat’ Parizhskoy Kommuny"},
{"id":8,"first_name":"Sylas","email":"sarnli7@upenn.edu","location":"Kokemäki"},
{"id":9,"first_name":"Melantha","email":"mlace8@cnet.com","location":"Yên Lạc"},
{"id":10,"first_name":"Titus","email":"tvoice9@eepurl.com","location":"Leśna Podlaska"},
{"id":11,"first_name":"Sharl","email":"sgoosea@comsenz.com","location":"Lukou"},
{"id":12,"first_name":"Hort","email":"hchristoforoub@booking.com","location":"Muritiba"},
{"id":13,"first_name":"Kendell","email":"koloughanec@nature.com","location":"Huzhen"},
{"id":14,"first_name":"Even","email":"ebattertond@sphinn.com","location":"Naval"},
{"id":15,"first_name":"Harriett","email":"hbenoiste@stanford.edu","location":"Laval"},
{"id":16,"first_name":"Terrye","email":"ttugwellf@barnesandnoble.com","location":"Charras"},
{"id":17,"first_name":"Taber","email":"tmcconigalg@about.com","location":"Nāḩiyat Baḩār"},
{"id":18,"first_name":"Arline","email":"astollenbeckerh@google.com","location":"Harrisburg"},
{"id":19,"first_name":"Hughie","email":"hknighti@yellowpages.com","location":"Jhang Sadr"},
{"id":20,"first_name":"Tasha","email":"tstockeyj@wsj.com","location":"Yaojiagou"},
{"id":21,"first_name":"Davin","email":"dhruskak@photobucket.com","location":"Suwon-si"},
{"id":22,"first_name":"Raquel","email":"rjuggingsl@typepad.com","location":"Sanchahe"},
{"id":23,"first_name":"Chloris","email":"cspincksm@dagondesign.com","location":"Bekwai"},
{"id":24,"first_name":"Tanhya","email":"tyolen@wiley.com","location":"Dongying"},
{"id":25,"first_name":"Jordan","email":"jguthersono@abc.net.au","location":"Balibagan Oeste"},
{"id":26,"first_name":"Ulberto","email":"upawelkep@last.fm","location":"Fanhu"},
{"id":27,"first_name":"Koo","email":"kyakubovq@elpais.com","location":"Mem Martins"},
{"id":28,"first_name":"Kermit","email":"klebretonr@amazon.co.jp","location":"Majāz al Bāb"},
{"id":29,"first_name":"Lian","email":"lfilmers@deviantart.com","location":"Greensboro"},
{"id":30,"first_name":"Elicia","email":"ecoatt@nhs.uk","location":"Conde"},
{"id":31,"first_name":"Osborne","email":"obowlandu@state.gov","location":"Bertioga"},
{"id":32,"first_name":"Constantine","email":"cbrabonv@pinterest.com","location":"Al Fayyūm"},
{"id":33,"first_name":"Rudolph","email":"rpaintenw@yahoo.com","location":"Kropotkin"},
{"id":34,"first_name":"Ange","email":"akleehuhlerx@php.net","location":"As Samawah"},
{"id":35,"first_name":"Emilia","email":"estolbergery@paypal.com","location":"San Felipe"},
{"id":36,"first_name":"Tedda","email":"tdungayz@deliciousdays.com","location":"Tanggung"},
{"id":37,"first_name":"Athena","email":"avillage10@meetup.com","location":"Namysłów"},
{"id":38,"first_name":"Caresa","email":"cmanville11@arstechnica.com","location":"Port Glaud"},
{"id":39,"first_name":"Ragnar","email":"rspradbrow12@blinklist.com","location":"Daxi"},
{"id":40,"first_name":"Darcie","email":"dwingfield13@toplist.cz","location":"Panggungwinong"},
{"id":41,"first_name":"Herve","email":"hwitherington14@altervista.org","location":"Kaustinen"},
{"id":42,"first_name":"Maegan","email":"mmorfett15@adobe.com","location":"Port-de-Paix"},
{"id":43,"first_name":"Frannie","email":"femmines16@i2i.jp","location":"Yabluniv"},
{"id":44,"first_name":"Morlee","email":"mmowling17@scientificamerican.com","location":"Bajia"},
{"id":45,"first_name":"Marcile","email":"mtullis18@oakley.com","location":"Naberezhnyye Chelny"},
{"id":46,"first_name":"Barbee","email":"bbewlie19@about.me","location":"L'Assomption"},
{"id":47,"first_name":"Jourdain","email":"jlowmass1a@gnu.org","location":"Arias"},
{"id":48,"first_name":"Dennison","email":"dconman1b@noaa.gov","location":"Stochov"},
{"id":49,"first_name":"Inigo","email":"ihallward1c@marketwatch.com","location":"Dinjo"},
{"id":50,"first_name":"Hamilton","email":"hsouthern1d@geocities.jp","location":"Lelkowo"},
{"id":51,"first_name":"Colas","email":"csture1e@theguardian.com","location":"Słubice"},
{"id":52,"first_name":"Travis","email":"tbrunelli1f@twitter.com","location":"Qianhong"},
{"id":53,"first_name":"Sandro","email":"sbaudinelli1g@bizjournals.com","location":"Pailiao"},
{"id":54,"first_name":"Westbrooke","email":"wmaccarrane1h@instagram.com","location":"Pokhara"},
{"id":55,"first_name":"Elsbeth","email":"ecomer1i@wikimedia.org","location":"Vryburg"},
{"id":56,"first_name":"Melesa","email":"mkirvell1j@ox.ac.uk","location":"Wiset Chaichan"},
{"id":57,"first_name":"Shandeigh","email":"soak1k@army.mil","location":"Nador"},
{"id":58,"first_name":"Fidel","email":"fbarradell1l@umn.edu","location":"Jam"},
{"id":59,"first_name":"Ninnette","email":"ncockroft1m@woothemes.com","location":"Tangyu"},
{"id":60,"first_name":"Terrence","email":"tlestrange1n@arstechnica.com","location":"Phu Kradueng"},
{"id":61,"first_name":"Doug","email":"dpostan1o@vinaora.com","location":"Podgórzyn"},
{"id":62,"first_name":"Melly","email":"mvigrass1p@webeden.co.uk","location":"Hirado"},
{"id":63,"first_name":"Issie","email":"ifabri1q@cloudflare.com","location":"Buliu"},
{"id":64,"first_name":"Maximilien","email":"mbrimilcome1r@jigsy.com","location":"Słońsk"},
{"id":65,"first_name":"Neall","email":"nmcareavey1s@adobe.com","location":"Comalapa"},
{"id":66,"first_name":"Emmy","email":"emackerness1t@reddit.com","location":"Pretana"},
{"id":67,"first_name":"Christabel","email":"cmatyas1u@pinterest.com","location":"Vetluzhskiy"},
{"id":68,"first_name":"Angelina","email":"asansome1v@pen.io","location":"Cevicos"},
{"id":69,"first_name":"Stanly","email":"sleser1w@loc.gov","location":"Blažovice"},
{"id":70,"first_name":"Casandra","email":"cqueste1x@histats.com","location":"Agpangi"},
{"id":71,"first_name":"Damon","email":"dleipnik1y@oakley.com","location":"Shīeli"},
{"id":72,"first_name":"Genna","email":"gderoche1z@123-reg.co.uk","location":"Xishaqiao"},
{"id":73,"first_name":"Bel","email":"bmacian20@dedecms.com","location":"Fushan"},
{"id":74,"first_name":"Ardath","email":"avokins21@squidoo.com","location":"Nanpiao"},
{"id":75,"first_name":"Reade","email":"rannakin22@npr.org","location":"Türkmenbaşy"},
{"id":76,"first_name":"Felicity","email":"fgealy23@merriam-webster.com","location":"New Leyte"},
{"id":77,"first_name":"Cleon","email":"cfullager24@addthis.com","location":"Najiaying"},
{"id":78,"first_name":"Morgan","email":"mcornillot25@macromedia.com","location":"Nezlobnaya"},
{"id":79,"first_name":"Madelena","email":"mwolters26@army.mil","location":"Tower"},
{"id":80,"first_name":"Leicester","email":"ldawby27@archive.org","location":"Klatakan"},
{"id":81,"first_name":"Garnette","email":"groberti28@theatlantic.com","location":"Buliran"},
{"id":82,"first_name":"Caritta","email":"cbloor29@archive.org","location":"Saurimo"},
{"id":83,"first_name":"Dorian","email":"dprettyman2a@qq.com","location":"Banjar Jambe Baleran"},
{"id":84,"first_name":"Emalia","email":"egrevatt2b@ted.com","location":"Duanshen"},
{"id":85,"first_name":"Emmey","email":"eslocom2c@geocities.jp","location":"Kuče"},
{"id":86,"first_name":"Clarisse","email":"cworg2d@naver.com","location":"Pasirnangka"},
{"id":87,"first_name":"Jeannie","email":"jcarthy2e@pinterest.com","location":"Närpes"},
{"id":88,"first_name":"Avril","email":"aivatt2f@xrea.com","location":"Urechcha"},
{"id":89,"first_name":"Alec","email":"ashingles2g@uiuc.edu","location":"Cisitu"},
{"id":90,"first_name":"Mischa","email":"mscarratt2h@nbcnews.com","location":"Shangmofang"},
{"id":91,"first_name":"Jorie","email":"jerrichiello2i@examiner.com","location":"Chicama"},
{"id":92,"first_name":"Romola","email":"rspradbrow2j@wp.com","location":"Buarcos"},
{"id":93,"first_name":"Ynez","email":"ycoltart2k@cmu.edu","location":"Navotas"},
{"id":94,"first_name":"Zuzana","email":"zcollelton2l@examiner.com","location":"Buang"},
{"id":95,"first_name":"Jimmy","email":"jdore2m@bravesites.com","location":"Khovd"},
{"id":96,"first_name":"Clementia","email":"chuthart2n@aol.com","location":"Chixi"},
{"id":97,"first_name":"Evangeline","email":"ebouch2o@infoseek.co.jp","location":"Wangshi"},
{"id":98,"first_name":"Bobinette","email":"biannazzi2p@creativecommons.org","location":"Aībak"},
{"id":99,"first_name":"Justinn","email":"jbishop2q@weebly.com","location":"Łazy"},
{"id":100,"first_name":"Lodovico","email":"lrustman2r@ifeng.com","location":"Nasīrābād"}]
for(x of cust_data){
   // console.log(cust_data);
    console.log(x.id);
}
for(i=0;i<=cust_data.length-1;i++){
    console.log(cust_data[i].email);
    console.log(cust_data[i].id);
    console.log(cust_data[i].location);
    console.log(cust_data[i].id,cust_data[i].email,cust_data[i].location);
    
}